/*
MySQL Data Transfer
Source Host: localhost
Source Database: food_recipe
Target Host: localhost
Target Database: food_recipe
Date: 19-04-2023 21:14:28
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for dish_details
-- ----------------------------
DROP TABLE IF EXISTS `dish_details`;
CREATE TABLE `dish_details` (
  `dish_id` int(10) NOT NULL auto_increment,
  `dishname` varchar(50) default NULL,
  `type` varchar(20) default NULL,
  `category` varchar(20) default NULL,
  `ingredients` varchar(100) default NULL,
  `description` varchar(100) default NULL,
  `preparation_process` varchar(150) default NULL,
  PRIMARY KEY  (`dish_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for item_details
-- ----------------------------
DROP TABLE IF EXISTS `item_details`;
CREATE TABLE `item_details` (
  `Meal_Id` varchar(50) NOT NULL,
  `Name` varchar(200) NOT NULL,
  `catagory` varchar(200) NOT NULL,
  `description` varchar(2000) NOT NULL,
  `Veg_Non` varchar(50) NOT NULL,
  `Nutrient` varchar(500) NOT NULL,
  `preparation_process` varchar(1000) NOT NULL,
  PRIMARY KEY  (`Meal_Id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for login
-- ----------------------------
DROP TABLE IF EXISTS `login`;
CREATE TABLE `login` (
  `uname` varchar(40) NOT NULL,
  `password` varchar(40) NOT NULL,
  `utype` varchar(40) NOT NULL,
  PRIMARY KEY  (`uname`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for payment_details
-- ----------------------------
DROP TABLE IF EXISTS `payment_details`;
CREATE TABLE `payment_details` (
  `tid` int(5) NOT NULL auto_increment,
  `user` varchar(15) default NULL,
  `ids` varchar(100) default NULL,
  `names` varchar(100) default NULL,
  `total` varchar(100) default NULL,
  `tdate` varchar(40) default NULL,
  `card` varchar(20) default NULL,
  `name` varchar(40) default NULL,
  `year` varchar(10) default NULL,
  `month` varchar(10) default NULL,
  `status` varchar(15) default NULL,
  PRIMARY KEY  (`tid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for user_details
-- ----------------------------
DROP TABLE IF EXISTS `user_details`;
CREATE TABLE `user_details` (
  `fname` varchar(40) NOT NULL,
  `lname` varchar(40) default NULL,
  `email` varchar(40) NOT NULL,
  `mobile` varchar(40) NOT NULL,
  `address` varchar(100) default NULL,
  `gender` varchar(20) NOT NULL,
  `password` varchar(20) NOT NULL,
  PRIMARY KEY  (`email`,`mobile`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for user_favourite_details
-- ----------------------------
DROP TABLE IF EXISTS `user_favourite_details`;
CREATE TABLE `user_favourite_details` (
  `userid` varchar(40) default NULL,
  `meal_id` varchar(30) default NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records 
-- ----------------------------
INSERT INTO `dish_details` VALUES ('2', 'Chicken Fried Rice', 'Dinner', 'Non-Veg', 'Rice#Oil#Salt#Onion#Chilli Powder#Chicken#Curd', 'Rice and chicken mixed Fired Rice', 'Fry and Boil together');
INSERT INTO `dish_details` VALUES ('3', 'Masala Dosa', 'Breakfast', 'Veg', 'Rice Powder#Oil#Potato#Onion#Green chilli', 'potato masala stuffed in dosa', 'fry rice power mix and put potato mix');
INSERT INTO `dish_details` VALUES ('4', 'Maggi', 'Breakfast', 'Veg', 'Rice Powder#Oil#Potato#Onion#Green chilli#maggi', 'however', 'dfdfdfdvg');
INSERT INTO `item_details` VALUES ('meal_id1', 'summer squash salad', 'salad', 'white balsamic vinegar# lemon juice# lemon rind# red chillies# garlic cloves  crushed # olive oil# summer squash  zucchini # sea salt# black pepper# basil leaves', 'veg', 'fiber', 'NA');
INSERT INTO `item_details` VALUES ('meal_id10', 'broccoli and almond soup', 'soup', 'vegetable stock# broccoli# ground almonds  toasted # skimmed milk# salt# freshly ground black pepper', 'veg', 'vitamin_c', 'NA');
INSERT INTO `item_details` VALUES ('meal_id100', 'spicy chicken curry', 'chicken', 'oil# ghee# onion paste# garlic paste# ginger paste# turmeric powder# salt# tomato puree# coriander powder# red chilli powder# cumin powder# garam masala# chicken leg pieces# coriander leaves# water', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id101', 'crispy herb chicken', 'chicken', 'fresh breadcrumbs# parmesan cheese# lemon rind# fresh parsley leaves# garlic powder# plain flour# egg# milk# chicken breast supremes# vegetable oil# mayonnaise# sour cream# fresh chives  dried if fresh not available # fresh parsley  dried if fresh not available # garlic# red onion  optional # ground black pepper# salt', 'non-veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id102', 'dahi chicken', 'chicken', 'dahi# cumin powder# garlic paste# garam masala# turmeric powder# red chilli powder# salt# boneless chicken# oil# green chilli# onion# tomato', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id103', 'amritsari chicken masala', 'chicken', 'chicken# ginger garlic paste# curd# lemon juice# vinegar# coriander powder# cumin powder# red chilli powder# salt# onion# butter# red chilli powder# coriander powder# cumin powder# ginger# water# salt# green chilli# tomatoes# sugar# butter # cream', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id104', 'chilli chicken', 'chicken', 'boneless chicken# salt# cornflour# black pepper# egg# soy sauce# red chilli sauce# garlic# green chillies# green chilli sauce# vinegar# onion# capsicum# black pepper# salt', 'non-veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id105', 'oat crusted chicken tenders', 'chicken', 'chicken breast  cut into strips # salt# garlic paste# ginger paste# green chilli paste# oats# refined flour# salt# freshly ground black pepper# fried mixed herbs  italian herb # garlic powder', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id106', 'chicken nimbu dhaniya shorba', 'chicken', 'water# chicken  diced  # ginger garlic paste# coriander# lemon# cream# butter# turmeric powder# green chilli paste# cornflour# salt', 'non-veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id107', 'garlic soya chicken', 'chicken', 'chicken thigh/breast  cut crosswise into 1/2-inch-thin strips # sesame oil  toasted # white pepper  finely ground # ginger juice# peanut oil or vegetable oil  divided # garlic cloves  minced # ginger# red chilli flakes# red onion # snow peas  trimmed # red bell pepper  cut into thin strips # rice vinegar# soy sauce# dark soy sauce# chinese rice wine# brown sugar# cornflour', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id108', 'cauliflower and chicken biryani', 'chicken', 'boneless chicken# biryani masala# yogurt# onions# coconut oil# cauliflower# coconut  diced # onion  diced # peppercorns# cardamoms# cumin seeds# bay leaves# cinnamon# cloves# coconut oil# garam masala# dry chilli flakes# turmeric powder# black peppercorns# cardamom# cinnamon# garlic  crushed # tomato puree# green chillies# fresh ginger  peeled # dry red chilli# salt', 'non-veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id109', 'chicken quinoa biryani', 'chicken', 'onions# tomato# green chillies slit open # ginger garlic paste# mint leaves# coriander leaves/cilantro# fresh yogurt/curd beaten # turmeric powder# chilli powder# salt# chicken  cut into pieces # garam masala powder# ginger garlic paste# yogurt/curd#  chilli powder# coriander powder# salt# oil# cloves# bay leaf # cardamom', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id11', 'coconut lime quinoa salad', 'salad', 'uncooked quinoa# water# red onion# cucumber  diced # purple cabbage# avocado  ripened and diced # orange# shelled edamame  defrosted # unsweetened toasted coconut flakes# almonds# few shakes of black pepper# for the dressing:# orange juice# lime  juiced # apple cider vinegar# olive oil', 'veg', 'fiber', 'NA');
INSERT INTO `item_details` VALUES ('meal_id110', 'chicken and mushroom lasagna', 'chicken', 'chicken# salt# crush black pepper# garlic cloves  minced # olive oil# fresh thyme# button mushroom# onion# low fat milk# basil# basil-tomato sauce', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id111', 'plum and cherry roasted chicken', 'chicken', 'carrot  finely diced # onion  finely diced # celery  finely diced # fresh thyme sprigs# whole free range chicken # pepper  freshly ground # parsley stems# celery leaves# lemon slices  1/8 inch thick # onion# carrot# fresh lemon juice# chicken stock/broth# plums  cut # fresh cherries', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id112', 'chicken roulade', 'chicken', 'chicken breasts# olives# jalapenos# bell peppers all 3 # thyme dried# white wine# salt# black pepper  crushed to taste # egg# olive oil# mozerella cheese# processed cheese', 'non-veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id113', 'sticky rum chicken wings', 'chicken', 'chicken wings without skin# hung curd# chilli powder# sweet paprika powder# english mustard paste# garlic paste# salt# garlic# rum# bbq sauce', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id12', 'lemon honey glazed sous vide corn on the cob', 'corn', 'young corn on the cob# honey# lemon juice# garlic cloves  smashed # celery stalk# chives# carrot# salt# paprika powder# parsley# plastic bag# food thermometer', 'non-veg', 'protien', 'NA');
INSERT INTO `item_details` VALUES ('meal_id126', 'andhra crab meat masala', 'meat', 'processed crab meat# refined oil# curry leaves# garlic# green chilli# onion# ginger-garlic paste# coriander# coriander powder# cumin powder# turmeric powder# garam masala powder# kashmiri chilli powder# salt# lemon# chop masala# tomato', 'non-veg', 'potassium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id127', 'cajun spiced turkey wrapped with bacon', 'meat', 'turkey breast# cajun spice# spinach leaves  cooked and drained # garlic pods# salted butter# feta cheese# bacon strips# ground black pepper# for cajun spice:# onion powder# garlic powder# seasoning salt# paprika# ground black pepper# cayenne pepper# oregano# thyme# red pepper flakes  if you like it spicy  ', 'non-veg', 'vitamin_c', 'NA');
INSERT INTO `item_details` VALUES ('meal_id128', 'mongolian lamb balls', 'meat', 'lamb  minced # couscous# scallion# garlic# egg# parsley# olive oil# mint# ao nori herb# salt# five spice# cinnamon powder', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id129', 'oyster lamb', 'meat', 'vegetable oil# garlic# ginger# lamb# stock# oyster sauce# dry sherry# sugar# celery# salt# bokchoy# shitake mushroom', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id13', 'watermelon and strawberry smoothie', 'smoothie', 'fresh strawberries# honey# low fat yogurt# watermelon# chia seeds', 'veg', 'magnesium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id130', 'chicken shami kebab', 'meat', 'oil# cumin seeds# cloves# black peppercorns# cinnamon# coriander seeds# ajwain# red chilli whole# chilli flakes# boneless chicken# salt# water# ginger# green chilli# garlic# coriander leaves # mint leaves # egg', 'non-veg', 'phosphorus', 'NA');
INSERT INTO `item_details` VALUES ('meal_id131', 'balti meat', 'meat', 'refined oil# black cardamoms# green cardamoms# mace# clove# cinnamon stick# black pepper corn# ginger garlic paste# ginger# green chilies# mutton curry cut# brown onion paste# salt# kashmiri red chili powder# tomato puree# garam masala powder# coriander powder# cumin powder', 'non-veg', 'potassium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id132', 'coffee marinated mutton chops', 'coffee', 'mutton chops# espresso# honey# balsamic vinegar# rosemary# pink peppercorns  crushed # olive oil# salt', 'non-veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id133', 'sali boti  parsi meat dish ', 'meat', 'mutton  wash and cut into very small cubes # ghee or oil# tomatoes# onions# green chillies# coriander leaves# chilli powder# turmeric powder# ginger-garlic paste# water# vinegar# jaggery# salt# potatoes# oil', 'non-veg', 'potassium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id136', 'malabari fish curry', 'curry', 'sear fish# coconut# ginger# pureed tamarind# salt# powdered turmeric# green chillies# red chilli powder# shallots', 'non-veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id137', 'portugese fish stew', 'fish', 'sole fillet  you can also do 2/3 types of fish # large shrimps  optional # potatoes  peeled # onions  cut into slices # garlic cloves# red capsicum  can use green also # parsley or coriander  choose the herb that most suits your taste buds # few dashes of hot sauce# paprika# olive oil# white wine# rock salt', 'non-veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id138', 'malabar fish curry', 'curry', 'whole coriander seeds# whole red chilli# coconut oil# mustard seeds# onion# curry leaf# coconut milk# tamarind pulp# coriander# seabass fish curry cuts', 'non-veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id139', 'surmai curry with lobster butter rice', 'rice', 'tamarind# red chilli powder# turmeric powder# salt# fresh coconut# onion# garlic cloves# coriander seeds# fenugreek seeds# red chilli powder# turmeric powder# tamarind  lemon sized # butter# lobster  de-shell and devein and make a small cube # salt and lime# surmai', 'veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id14', 'peach# raspberry and nuts smoothie', 'smoothie', 'fresh raspberries# ripe banana# almond# fresh peach slices# low fat yogurt# fresh raspeberry# peach fruit slices# almonds', 'veg', 'vitamin_e', 'NA');
INSERT INTO `item_details` VALUES ('meal_id140', 'seared salmon in tabasco butter', 'butter', 'butter# tabasco# chives# salt# salmon fillet# olive oil# sea salt', 'non-veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id141', 'risotto lobster with parmesan egg pancake# confit tomatoes and coral tuille', 'egg', 'lobster shell# carrot# leeks# garlic cloves# tomato paste# bay leaf# peppercorn# water# lobster meat# arborio rice# onion# leeks# lobster stock# parmesan cheese# cream# salt# olive oil# egg# parmesan# flour# milk# parsley# salt# cherry tomatoes# garlic pods# olive oil# water# oil# flour# salt', 'non-veg', 'vitamin_c', 'NA');
INSERT INTO `item_details` VALUES ('meal_id142', 'fish skewers with coriander and red wine vinegar dressing', 'wine', 'sea bass fillets# olive oil  for grilling # red wine vinegar# sugar# extra virgin olive oil# garlic clove# coriander# bamboo skewers', 'non-veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id143', 'seafood rock filler', 'baked', 'baked tart of mixed sea food served with phyllo fruit bowl# savory tart shell  semi baked # mixed sea food# mornay sauce# assorted herb and seasoning# phyllo pastry# assorted seasonal fruit', 'veg', 'iodine', 'NA');
INSERT INTO `item_details` VALUES ('meal_id144', 'shrimp &amp; cilantro ceviche', 'coriander', 'prawns# gherkin# onion# cilantro# mix bell pepper# tiger milk# sweet corn# sea salt# black pepper# green lemon juice# cherry tomato# edible flower# coriander stems# celery stalks# garlic# ginger# red onion# lemon juice# sea salt# black pepper', 'veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id145', 'saewoo bokumbop  shrimp fried rice ', 'egg', 'cooked rice# shrimp  de-veined# onion# cooked green peas# green onion# egg  scrambled # vegetable oil/butter# soy sauce# sesame oil# salt# pepper', 'veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id146', 'goan prawn curry &amp; baked rice canapes', 'rice', 'jeera whole# coriander seeds# kashmiri chilly# garlic# ginger# green chillies# kokum# coconut# onion# tomatoes# coriander# prawns# salt# turmeric powder# garlic paste# asafoetida# refined oil# ginger paste# goan rice# coconut milk# green chillies# fresh coconut# hing# refined oil# coriander leaves# basmati rice# coconut milk# green chillies# coconut milk# coconut# salt# green chillies# curry leaf# lecite', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id147', 'bihari fish curry', 'curry', 'rohu fish# salt# turmeric powder# chilli powder# oil# garlic # green chillies# mustard seeds# black peppercorns# cumin seeds# whole red chillies# fenugreek seeds# tomatoes# mustard oil# bay leaves# water# garam masala# coriander leaves', 'non-veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id148', 'beer batter fish fingers', 'fish', 'river sole fish  cut in thin strips # garlic paste# salt # lime juice# beer# flour# cornflour# white pepper# eggs# mustard', 'non-veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id149', 'prawn and litchi salad', 'salad', 'prawns  shelled and cleaned # spring onions# mango flesh# litchis  deseeded # chilli flakes# lemon  for lemon juice # olive oil# peanuts  to garnish # salt', 'veg', 'fiber', 'NA');
INSERT INTO `item_details` VALUES ('meal_id15', 'almond and cranberry poha', 'poha', 'almond flakes# onion# poha# cranberries  frozen/ dried # salt# oil# curry leaves# green chilies# fresh coconut', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id150', 'kerala fish curry', 'curry', 'white fish  cut into cubes # onion# tomato# garlic cloves# fresh green chillies  deseeded # oil# fresh coconut paste# red chilli paste# coriander powder# turmeric powder# salt# whole dry red chillies# black mustard seeds# curry leaves# tamarind extract# water', 'non-veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id151', 'fish andlouse', 'fish', 'white wine and water mix to cover# onion# salt# bay leaf# black pepper corns# olive oil# onion# garlic# tomatoes  peeled and seeded # basil leaves# spring fresh thyme - optional 1 bay leaf# salt and pepper# olive oil# wine vinegar# prepared mustard# salt and pepper# assorted garden herbs   parsley# basil etc.', 'non-veg', 'vitamin_c', 'NA');
INSERT INTO `item_details` VALUES ('meal_id16', 'almond and raw banana galawat', 'banana', 'almond slivers# raw banana  boiled # almond paste# cooking cream# refined oil# mace powder# cardamom powder # ginger garlic paste# garam masala powder# red chilli powder# salt# tempura batter', 'veg', 'selenium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id163', 'red rice vermicelli kheer', 'rice', 'red rice vermicelli / broken sooji / semolina vermicelli# butter# almonds# whole milk# cardamom powder# saffron strands / thread# sugar', 'veg', 'carbohydrates', 'NA');
INSERT INTO `item_details` VALUES ('meal_id164', 'green cucumber shots', 'rice', 'english cucumbers# garlic cloves  smashed # romaine lettuce# basil# parsley# cilantro# big lemon# sea salt# olive oil', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id165', 'thai pineapple rice', 'rice', 'rice# onion# thai ginger # fresh turmeric# curry leaf# lemon grass# coconut milk# salt# hot curry powder# pineapple chunks# oil# water# turmeric powder# fresh pineapple', 'veg', 'carbohydrates', 'NA');
INSERT INTO `item_details` VALUES ('meal_id166', 'green asparagus risotto', 'rice', 'carnaroli rice# vegetable broth# butter# extra virgin olive oil# parmigiano cheese# onion  minced # white wine# salt & pepper', 'veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id167', 'veg fried rice', 'rice', 'oil# ginger-garlic paste# spring onion# carrot# cabbage# capsicum# salt# soy sauce# vinegar# rice', 'veg', 'carbohydrates', 'NA');
INSERT INTO `item_details` VALUES ('meal_id168', 'egg and garlic fried rice', 'rice', 'oil# garlic# spring onion # ginger# red chilli # egg# cooked rice# salt# black pepper powder# soya sauce', 'non-veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id169', 'curd rice', 'rice', 'rice# water# curd# milk# carrot# green chilli# ginger# salt# coriander leaves# oil# mustard seeds# chana dal# urad dal# curry leaves# red chilli# hing', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id17', 'baked namakpara with roasted almond dip', 'dip', 'almonds  crushed # tomato# garlic cloves# basil sprig# lemon# salt# pepper# for namak para:# refined flour# sugar# salt# olive oil# water', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id170', 'fried rice with soya chunks', 'rice', 'basmati rice# carrot# capsicum# beans# green peas# ginger# garlic# green chillies# bay leaf# cinnamon sticks# green cardamoms# clove# soya chunks# salt#', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id171', 'corn pulao', 'rice', 'basmati rice# american corn kernels# olive oil# onion# ginger garlic paste# salt# green chillies# cumin seed# bay leaf# pepper corn# cloves# hot water# coriander leaves# lime juice# bell pepper  sautéed and diced # coconut', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id172', 'zucchini methi pulao', 'rice', 'zucchini# basmati rice# fenugreek  methi # clarified butter  desi ghee # clarified butter  desi ghee # cumin seeds  jeera # asafoetida  heeng # green chilles# ginger# salt', 'veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id173', 'lemon rice', 'rice', 'cooked basmati rice# oil# asafoetida  heeng # mustard seeds  sarson # curry leaves  kadhi patta # whole red chilli  sabut laal mirch # turmeric powder haldi # salt# lemon juice# peanuts# urad dal# chana dal# ginger', 'veg', 'magnesium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id174', 'kale channe ki biryani', 'rice', 'black gram  kala chana # basmati rice  soaked for 2 hours # cinnamon# green cardamoms# cloves# ghee# black cardamoms# black peppercorns# bay leaves# onions# green chillies  slit # ginger-garlic paste# coriander powder# turmeric powder# yogurt# fresh mint leaves# fresh coriander leaves# garam masala powder# red chilli powder# salt# cashew nuts# almonds# milk# fresh cream# saffron# ginger# screw pine essence  kewra # browned onions# whole wheat flour dough', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id175', 'chicken paella', 'rice', 'chicken# oil# salt and pepper# paprika powder# chilli flakes# garlic paste# onions# bell peppers# rice# vegetable stock# saffron# peas# olives# parsley# white wine', 'non-veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id176', 'thai fish curry', 'rice', 'fish  cubed # thai green curry paste# oil# onions# garlic# ginger/galangal# coconut milk# coriander# lemon juice# palm sugar# basil leaves# salt & pepper', 'non-veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id177', 'vegetable pulao', 'rice', 'water# basmati rice# ghee# paneer  cooked # carrot# beans# peas# elaichi# cardamoms# cinnamon# bay leaves# cumin seeds# chilli powder# turmeric# salt# coriander leaves', 'veg', 'phosphorus', 'NA');
INSERT INTO `item_details` VALUES ('meal_id18', 'grilled almond barfi  sugar free ', 'barfi', 'khoya# sweetener  optional # almonds  crushed ', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id184', 'vegetable bruschetta', 'bread', 'baguette  grilled slices # black olive tapenade# artichoke hearts# lettuce arugula  trummed # tomato confit# fresh basil leaves# mint leaves# zucchini# goat cheese# parmesan cheese shavings# mozzarella buffalo cheese', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id185', 'red wine braised mushroom flatbread', 'wine', 'olive oil# fresh buffalo mozzarella cheese# canned pelati tomatoes  cooked # pizza/flatbread base# mushrooms# red wine# parsley# garlic cloves  halved # salt', 'veg', 'vitamin_c', 'NA');
INSERT INTO `item_details` VALUES ('meal_id186', 'strawberry &amp; pistachio breton tart', 'bread', 'plain flour# baking powder# sea salt# unsalted butter# egg yoks# castor sugar# double cream# yolk# sugar# gelatine# butter# pistachio paste# strawberry', 'veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id187', 'tricolour pizza', 'bread', 'pizza base # pizza sauce# mozzarella cheese# black olive# green capsicum# carrots# olive oil', 'veg', 'sodium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id188', 'instant rava dosa', 'bread', 'rava/suji/semolina# rice flour# all purpose flour# fresh coconut  pieces # jeera# green chilli# dhaniya# onion  diced # salt# water# oil# ghee/clarified butter', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id189', 'easy bread poha', 'bread', 'oil# hing# mustard seeds# curry leaves# whole red chillies# cookes peas# peanuts# turmeric powder# salt# bread# green chillies# lemon juice# coriander leaves# dessicated coconut', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id19', 'baked shankarpali recipe', 'shankarpali', 'whole wheat flour  atta # refined flour  maida # garlic cloves  crushed # salt# red chilli powder# chaat masala# cumin powder# tomato puree# ghee', 'veg', 'carbohydrates', 'NA');
INSERT INTO `item_details` VALUES ('meal_id190', 'bread chana basket', 'bread', 'bread  white/brown # butter# for chana chaat:# chana# onion# tomatoes# cumin seeds# ginger garlic paste# chilli powder# chana masala# turmeric powder # oil# salt', 'veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id191', 'spaghetti with clams &amp; crispy bread crumbs', 'bread', 'panko# 1/4 cup plus 1 tablespoon extra-virgin olive oil# plus more for drizzling# kosher salt# freshly ground pepper#  garlic cloves#  manila clams or cockles# scrubbed# dry white wine#  spaghetti#  lemon zest#  lemon juice#  mullet bottarga  optional; see note #   red pepper#  thyme#  rosemary#  parsley', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id192', 'kasha bread', 'bread', 'kasha# boiling water# buckwheat flour# all-purpose gluten free flour# brown sugar# baking powder# baking soda# xanthum gum# salt# buttermilk# cream# egg# oil# walnuts', 'veg', 'selenium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id193', 'egg paratha', 'bread', 'whole wheat flour# salt# oil# eggs# onions# green chilli# coriander leaves# garam masala', 'non-veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id194', 'egg and cheddar cheese sandwich', 'bread', 'egg# salt# pepper# ham slices# basil leaves', 'non-veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id195', 'egg in a blanket', 'bread', 'eggs# brown bread slices# butter# chilli flakes# oregano# salt', 'non-veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id196', 'bread dahi vada', 'bread', 'bread slices# curd# oil# salt and black pepper # red chilli powder# aamchoor powder# mint leaves# zeera powder# anardana', 'veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id199', 'lemon poppy seed cake', 'cake', 'plain flour# baking powder# salt# castor sugar# baking soda# eggs# butter# vanilla essence# lemon juice# poppy seed# lemon peel# to serve:# lemon syrup# whip cream# fresh berry', 'veg', 'potassium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id2', 'chicken minced salad', 'salad', 'olive oil# chicken mince# garlic  minced # onion# salt# black pepper# carrot# cabbage# green onions# sweet chilli sauce# peanut butter# ginger# soy sauce# fresh cilantro# red pepper flakes  crushed # tarts', 'non-veg', 'fiber', 'NA');
INSERT INTO `item_details` VALUES ('meal_id20', 'baked multigrain murukku', 'baked', 'oats# ragi flour  bhakri atta # wheat flour# rice flour# urad dal flour  dry roast and grind the dal to a fine powder # cumin seeds# green chillies# ginger# salt# oil', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id200', 'chocolate kaju katli', 'kaju', 'cashew nuts# sugar# water# milk chocolate or dark chocolate', 'veg', 'vitamin_d', 'NA');
INSERT INTO `item_details` VALUES ('meal_id201', 'mix fruit laccha rabri tortilla crunch', 'rabri', 'milk# sugar# cardamom powder# saffron# almonds and pistachios# grapes# apple# kiwi# orange# pomegranate# mint leaves# tortilla sheet# oil', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id21', 'apple rabdi', 'rabdi', 'apples# milk# sugar# green cardamoms# almonds  blanched # pistachios  blanched ', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id211', 'lamb barley pot', 'barley', 'pot barley# onions# worcestershire sauce# chilli flakes# mustard seeds# thick mutton chunks# thick neck of lamb chops# water or stock  to cover # salt# black pepper  freshly ground ', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id212', 'al hachi chicken', 'chicken', 'shallow fried chicken# bottle gourd  boiled and sun dried # onion# garlic# whole spices:# green cardamom# black cardamom# cinnamon sticks# turmeric# deggi mirch# fennel seeds powder# dry ginger powder# coriander powder# salt# mustard oil# desi ghee', 'non-veg', 'magnesium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id213', 'berry parfait hazelnut white chocolate sable', 'chocolate', 'for berry parfait:# egg yolk# caster sugar# berry puree# cream cheese# double cream# for hazelnut streusel:# ground hazelnut# flour# caster sugar# butter# for hazelnut white chocolate pressed sable:# hazelnut streusel# cocoa butter# puffed rice# clarified butter# melted white chocolate# for flexy berry:# raspberry puree# sugar# liquid glucose# pectin', 'veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id216', 'duo of chocolate and strawberry', 'strawberry', 'dark chocolate# white chocolate# strawberries', 'veg', 'vitamin_c', 'NA');
INSERT INTO `item_details` VALUES ('meal_id217', 'mustard-parmesan whole roasted cauliflower', 'roasted', 'cauliflowers# garlic# halved# olive oil # dijon mustard # kosher salt # freshly ground black pepper # fresh parsley leaves# parmesan # lemon wedges', 'veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id218', 'hassel back sweet potatoes', 'vanilla', 'sweet potatoes# butter# brown sugar# pure vanilla extract# ground cinnamon# himalayan pink salt / rock salt', 'veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id219', 'mother christmas cake', 'cake', 'tart apples  2 large # sugar# apple juice# eggs# vegetable oil# vanilla extracts# all-purpose flour# apple pie spice  cinnamon # salt# pecans# candied red cherries  halved # candied green cherried  halved # candied pineapple  diced # cashews  optional ', 'veg', 'potassium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id22', 'baked namak para', 'baked', 'whole wheat flour  atta # refined flour  maida # baking powder# ghee# salt# carom seeds  ajwain ', 'veg', 'magnesium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id220', 'matcha tea macarons', 'tea', 'egg whites# breakfast sugar# icing sugar# almond powder# matcha powder# heavy cream# white chocolate', 'veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id221', 'amaranthus granola with lemon yogurt# berries and marigold', 'yogurt', 'popped amaranthus  cholai # oats# almonds# cinnamon powder# sunflower seeds# sesame seeds# honey# brown sugar# salt# olive oil# lemon rind# plain yogurt  whipped with lemon rind # blueberries', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id222', 'chocolate fudge cookies', 'cookie', 'dark chocolate coverture# butter# sugar# eggs# flour# baking powder# salt# cocoa powder# vanilla essence', 'veg', 'magnesium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id223', 'veg summer rolls', 'rice', 'rice paper sheets# iceberg lettuce# carrot# bean sprouts# cucumber# tofu# basil# mint leaves# coriander# rice noodles  soaked in warm water for 20-25 minutes # peanuts# hoisin sauce# peanuts# garlic# oil# red chillies# water', 'veg', 'carbohydrates', 'NA');
INSERT INTO `item_details` VALUES ('meal_id224', 'eggless vanilla cake', 'cake', 'maida# baking powder# castor sugar# butter# milk# vanilla essence# vinegar', 'veg', 'potassium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id225', 'sweet potato pie', 'pie', 'yams  red skinned # condensed milk# sugar# egg # cinnamon # marshmallows #', 'veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id226', 'wok tossed asparagus in mild garlic sauce', 'sauce', 'asparagus# 1 fried onion  medium # 1/2 tsp breakfast sugar# 10 ml potato starch# 20 ml stock vegetarian# 20 gm porcini# salt to taste# 50 ml oil', 'veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id227', 'cinnamon oatmeal pancakes', 'pancakes', 'rolled oats# buttermilk  divided # whole wheat flour or oat flour# baking powder# baking soda# cinnamon# salt# eggs# canola oil # honey or maple syrup#', 'veg', 'selenium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id228', 'chocolate chip cheesecake', 'chocolate', 'butter biscuits  broken into pieces # butter  softened # cream cheese  softened # sugar# egg# rose essence or vanilla essence# chocolate chips', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id229', 'chocolate lava cake', 'cake', 'dark chocolate# butter# icing sugar# egg yolks +  whole eggs# flour', 'veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id23', 'dates and nuts ladoo', 'ladoo', 'dates  pitted # mixed nuts  almonds# cashews# walnuts# pistachios# peanuts # dessicated coconut  optional ', 'veg', 'vitamin_e', 'NA');
INSERT INTO `item_details` VALUES ('meal_id230', 'eggless coffee cupcakes', 'coffee', 'maida/ flour# baking powder# sugar# cocoa powder# vanilla essence# butter  softened# salted. in case you are using unsalted butter# add 1/4 tsp salt # milk  to make the batter smooth. adjust the milk quantity according to your batter\'s smoothness # coffee powder + 1 tsp water# to make a paste  you can increase or decrease according to your coffee tolerance ', 'veg', 'vitamin_d', 'NA');
INSERT INTO `item_details` VALUES ('meal_id231', 'chicken in white wine', 'wine', 'black pepper# plain flour# olive or sunflower oil# rashers lean bacon# onions or shallots   cut in half # mushrooms# butter# boneless and skinless chicken breasts  chopped into 3cm pieces # dry white wine# chicken or vegetable stock# garlic cloves# bay leaves# fresh thyme sprigs  washed or 1/2 tsp dried thyme ', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id236', 'plum cake', 'cake', 'oven temp: 150 c-300 f# butter# sugar# eggs# almonds# vanilla essence# mixed fruits  sultanas# raisins# candied peels and cherries # refined flour#', 'veg', 'potassium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id238', 'holi special malai kofta', 'kofta', 'potatoes# paneer  cottage cheese # maida# coriander leaves  chopped # onion# ginger-garlic paste# tomatoes# malai or cream# raisins and cashew nuts# cashew nuts paste# haldi# red chilli powder# kitchen king masala# kasuri methi  dry fenugreek # salt# sugar', 'veg', 'phosphorus', 'NA');
INSERT INTO `item_details` VALUES ('meal_id239', 'homemade gulab jamun', 'gulab', 'sugar# water# milk# cardamom seeds# saffron# cardamom powder# khoya# baking soda# maida# milk', 'veg', 'vitamin_d', 'NA');
INSERT INTO `item_details` VALUES ('meal_id24', 'green lentil dessert fudge', 'dessert', 'whole moong beans# cow ghee# raisins# whole milk# jaggery  organic # ground cardamom# almonds  halved ', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id240', 'lamb rogan josh', 'lamb', 'lamb chops or stewing lamb# vegetable oil# cassia bark or cinnamon stick# bay leaves# green cardamoms# onions# garlic cloves# butter# turmeric# chilli powder# ground cumin# ground coriander# tomato puree# salt# garam masala# lemon juice', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id241', 'fish curry', 'curry', 'fresh sole fish# black pepper powder# lemon  juiced # onion# coriander seeds# black pepper# raw rice# garlic cloves# coconut# coriander leaves# ginger  large # cinnamon powder# clove powder# ground nut oil# tamarind paste# cooking oil# salt#', 'non-veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id242', 'rice kheer', 'kheer', 'milk# rice  washed # sugar# raisins# green cardamoms# almonds  shredded ', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id243', 'assorted rice kheer sushi', 'kheer', 'basmati rice# milk# sugar# pistachio# almonds# green cardamoms powdered # saffron# rose water# rose petals  dried # dark chocolate', 'veg', 'magnesium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id244', 'jalebi with fennel yogurt pudding', 'pudding', 'all purpose flour# yogurt# oil# sugar# water# saffron# green cardamom# yogurt  strained # milk  warm # sugar# nutmeg# cardamom powder', 'veg', 'vitamin_d', 'NA');
INSERT INTO `item_details` VALUES ('meal_id245', 'broccoli souffle', 'broccoli', 'broccoli# butter# extra virgin olive oil# all-purpose flour# low fat milk# salt# black pepper# cheddar cheese# eggs  separated # egg whites# cream of tarter', 'veg', 'vitamin_c', 'NA');
INSERT INTO `item_details` VALUES ('meal_id246', 'christmas dry fruit cake', 'cake', 'butter  at room temperature # dark brown sugar# eggs# flour# salt# all spice powder# cinnamon# nutmeg# currants; golden raisins; dark raisins  each # soft dried figs# dates  pitted # prunes  stoned dried # apricots  dried # almonds  chopped # brandy# instant espresso  mixed with 1 tbsp water ', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id247', 'microwave chicken steak', 'chicken', 'chicken breasts  boneless # eggs  slightly whisked # ginger paste# garlic paste# onions# coriander leaves# green chillies# black pepper powder# flour# vinegar# salt# oil', 'non-veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id248', 'cheese and ham roll', 'cheese', 'hung curd# butter# cream# ground pimento# lemon juice# vodka# salt and pepper# asparagus spears cooked # ham# pineapple slices', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id249', 'vegetable manchurian', 'tomato', 'mixed vegetables - chopped fine or grated# eggs  slightly beaten # refined flour# garlic paste# ginger paste# water# oil # garlic # onions # capsicum# cornflour  blended with water # vinegar# salt# soya sauce# tomato puree# celery# ajinomoto  optional # water', 'veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id25', 'cashew nut cookies', 'cookie', 'cashew paste# ghee# khaand  a sweetening agent and a healthier substitute of sugar # flax or chia seeds# plain yogurt# baking soda# baking powder# vanilla# oats# organic all-purpose flour', 'veg', 'protien', 'NA');
INSERT INTO `item_details` VALUES ('meal_id250', 'jerk chicken', 'chicken', 'chicken legs# lime  halved # jerk seasoning powder  bottled # jerk seasoning paste  bottled # olive oil', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id254', 'orange quinoa sevaiyan', 'almond', 'sevaiyan# quinoa# orange juice # dried figs# sugar# almond milk# desi ghee# jaggery# walnuts# melon seeds# peanuts', 'veg', 'protien', 'NA');
INSERT INTO `item_details` VALUES ('meal_id255', 'spicy creamy kadai chicken', 'chicken', 'chicken# ginger-garlic paste# pepper powder# lime juice# oil# salt# tomatoes# green chillies# ginger-garlic paste# chilli powder# black cardamoms# cloves# water# onion# ginger# green chillies# chilli powder# turmeric powder# garam masala# kasturi methi# cream', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id256', 'apple kheer', 'kheer', 'apples# basmati rice# nuscovado sugar  you can also use normal sugar # cashew nuts and almonds# cassia bark or cinnamon stick# red grapes', 'veg', 'vitamin_e', 'NA');
INSERT INTO `item_details` VALUES ('meal_id257', 'ragi oats ladoo  laddu ', 'ladoo', 'ragi flour# oats flour# dates  ripe # milk# honey# ghee# green cardamom powder# white sesame seeds# coconut powder# cashew nuts', 'veg', 'vitamin_e', 'NA');
INSERT INTO `item_details` VALUES ('meal_id258', 'lamb korma', 'korma', 'onions# almond paste# ghee# cinnamon sticks# green cardamom# cloves# mace# bay leaves# garlic paste# ginger paste# lamb# salt# rose water  infused with 4-5 strands of saffron # yellow chilli powder# yogurt# yellow chilli powder# black pepper powder# coriander seed powder# cumin powder# red chilli powder# turmeric powder# clove powder# green cardamom powder# rose petal powder# nutmeg powder# black cardamom powder# fennel powder# cinnamon powder# mace powder# onions# cream/malai', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id259', 'ragi coconut ladoo  laddu ', 'ladoo', 'finger millet flour  ragi # jaggery# peanuts# coconut# salt', 'veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id26', 'almond pearls', 'almond', 'toasted almonds# blueberries# oats# corn flakes# olive oil# salt# curry leaves# mustard seeds# cumin seeds# red chilli powder# turmeric powder# black pepper powder# ajwain# lemon juice', 'veg', 'protien', 'NA');
INSERT INTO `item_details` VALUES ('meal_id263', 'holi special bhang pakode', 'pakode', 'besan# potato# fresh bhang leaves# spinach# bhang seed powder# ajwain# fresh green chilly # salt# tamarind paste# red chilly powder# mustard seeds# whole red chilli# soda', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id264', 'kuttu atta pizza', 'pizza', 'kuttu atta# salt# sugar# yeast# mozzarella cheese fresh# tomato# basil# cottage cheese# green chillies# olive oil# salt# black pepper  crushed # oregano', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id265', 'arbi kofta with mint yogurt dip', 'dip', 'arbi/colocasia roots# water chestnut flour  kuttu ka aata # green chili# ginger# carom seeds# rock salt# oil# mint# curd# cucumber# pomegranate', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id266', 'puffed rice squares', 'rice', 'puffed rice# nuts# honey# jaggery# butter# kewda to flavor# cardamom powder', 'veg', 'carbohydrates', 'NA');
INSERT INTO `item_details` VALUES ('meal_id267', 'red velvet banana pudding', 'pudding', 'one can of sweetened condensed milk# ice cold water# instant vanilla pudding mix# cream cheese  softened and cut into 8 pieces # heavy cream# one 9 x 13 inch layer of red velvet cakcake# ripe bananas# mini chocolate chips# sugar# cocoa# cake flour# baking soda# salt# butter  room temp cut into 1 inch pieces # eggs# milk# sour cream# cider vinegar# vanilla extract# red food coloring# all-purpose flour# milk# unsalted butter  room temperature # sugar# vanilla extract', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id268', 'baked wild berry cheesecake', 'berry', 'butter# digestive biscuits# berries# cream cheese# castor sugar# vanilla extract# egg  lightly beaten # icing sugar', 'veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id269', 'spiced orange valencia cake', 'cake', 'egg whites# egg white powder# sugar# almond powder# hazelnut powder# sugar# hazelnut  toasted ', 'veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id27', 'hawaiin papaya salad', 'salad', 'papaya# fresh lime  juiced # watermelon balls or small squares  seedless # fresh pineapple chunks# coconut  unsweetened # vanilla flavoured yogurt  low fat ', 'veg', 'fiber', 'NA');
INSERT INTO `item_details` VALUES ('meal_id270', 'jalapeno cheese fingers', 'cheese', 'yellow cornmeal# sugar# baking soda# salt# buttermilk  well-shaken # egg# cheddar  extra sharp # scallion  white and pale green parts only # pickled jalapenos  drained # unsalted butter#', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id271', 'californian breakfast benedict', 'sauce', 'brioche loaf# avocado paste# eggs# tomato# spinach# nutmeg powder# phyllo pastry sheet# assorted seasonal fruits# hollandaise sauce', 'veg', 'protien', 'NA');
INSERT INTO `item_details` VALUES ('meal_id272', 'chocolate marquise', 'chocolate', 'dark chocolate  melted # castor sugar# egg yolk# egg# cocoa powder# coffee# cream# berries# dark chocolate# fresh cream', 'veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id273', 'corn &amp; jalapeno poppers', 'corn', 'fresh corn kernels# corn flour# whole egg# cheddar cheese# jalapeno poppers# smoked paprika# coriander  toasted & ground # green onions# fresh cilantro# lemon  zest and juice # cooking oil', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id274', 'banana phirni tartlets with fresh strawberries', 'banana', 'basmati rice  soaked in water # milk# cardamom powder# milk# saffron# sugar# banana# fresh strawberries# plain flour# butter  chilled # castor sugar# egg yolk# chilled water', 'veg', 'vitamin_c', 'NA');
INSERT INTO `item_details` VALUES ('meal_id279', 'mixed beans salad', 'salad', 'mixed boiled beans  choose from rajma# chawli# chick peas# hara chana # spring onions# tomatoes  diced # oil# lemon juice# basil# garlic# salt and pepper# for garnish:# coriander', 'veg', 'fiber', 'NA');
INSERT INTO `item_details` VALUES ('meal_id28', 'vegetable som tam salad', 'salad', 'raw papaya# carrot# french bean diamond# cherry tomato# garlic# crush mix chilli# somtam dressing# peanuts  crushed # peanuts', 'veg', 'fiber', 'NA');
INSERT INTO `item_details` VALUES ('meal_id280', 'baked raw banana samosa', 'samosa', 'onion# ginger# curry powder# fresh coriander# green chilli# raw banana paste# refined oil# mustard seeds# phyllo sheets# salt', 'veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id281', 'coconut mango oatmeal with cinnamon hint', 'mango', 'coconut  tender # coconut milk# oats# ripe mango  diced # castor sugar# dry fruits# honey# cardamom powder', 'veg', 'selenium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id282', 'fruit cube salad', 'salad', 'watermelon# cantaloupe# kiwifruiit# pineapple# marshmallow# mint leaf  crushed nuts# sesame seeds or cinnamon ', 'veg', 'fiber', 'NA');
INSERT INTO `item_details` VALUES ('meal_id283', 'veg hakka noodles', 'sauce', 'noodles# salt# oil# garlic paste# ginger paste# beans# cabbage# carrot# spring onion# capsicum# soy sauce# green chilli sauce# tomato sauce', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id284', 'strawberry quinoa pancakes', 'pancakes', 'quinoa# milk# olive oil# egg  slightly beaten # baking powder# orange essence# castor sugar# maple syrup# strawberries  to garnish ', 'veg', 'vitamin_c', 'NA');
INSERT INTO `item_details` VALUES ('meal_id289', 'amritsari fish', 'fish', 'with curry# ginger and garlic', 'non-veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id29', 'spinach and feta crepes', 'spinach', 'milk  whole fat or skimmed # flour# water# butter# honey# salt# vegetable oil# extra butter  for crisping the crepe # spinach# feta cheese  crumbled # greek yogurt  whisked # honey', 'veg', 'vitamin_c', 'NA');
INSERT INTO `item_details` VALUES ('meal_id290', 'butter chicken', 'chicken', 'rgh mahal', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id291', 'chicken razala', 'chicken', 'icken cooked in a rich gravy with mint', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id292', 'chicken tikka', 'tikka', 'ces served on a skewer', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id293', 'chicken tikka masala', 'tikka', 'd in a yogurt tomato sauce. creamy texture.', 'non-veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id294', 'mushroom matar', 'matar', 'eet peas in a masala/chili sauce', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id295', 'tandoori chicken', 'chicken', 'as a dish originated in the punjab before the independence of india and pakistan.', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id296', 'tandoori fish tikka', 'tikka', 'n lime and ginger and cooked over an open fire.', 'non-veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id297', 'chettinadu chicken', 'chicken', 'n and spices', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id298', 'chicken 65', 'chicken', 'ed chicken preparation. chicken# onion# ginger', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id299', 'kolim / jawla', 'fish', 'dried fish named kolim or jawla found in coastal maharashtra with onion and spices. usually eaten with bhakri or chapati', 'veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id3', 'sweet chilli almonds', 'chilli', 'almonds whole# egg white# curry leaves# salt# sugar  fine grain # red chilli powder', 'veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id30', 'couscous with ratatouille - tangy tomato sauce', 'sauce', 'for the cous cous:# plain couscous# extra virgin olive oil# vegetable stock# herbs  basil# parsley# thyme# cilantro work best # for the ratatouille:# olive oil  regular not extra virgin # red onions# aubergines  cut in to 3 cm cubes # zucchini  cut in to 3 cm cubes # garlic cloves# ground cumin# sweet paprika# tomato paste# salt', 'veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id300', 'black rice', 'rice', 'riety of rice', 'veg', 'carbohydrates', 'NA');
INSERT INTO `item_details` VALUES ('meal_id301', 'brown rice', 'rice', 'riety of rice.', 'veg', 'carbohydrates', 'NA');
INSERT INTO `item_details` VALUES ('meal_id302', 'koldil chicken', 'chicken', 'ith banana flower; an assamese specialty', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id303', 'red rice', 'rice', 'riety of rice.', 'veg', 'carbohydrates', 'NA');
INSERT INTO `item_details` VALUES ('meal_id304', 'rice', 'rice', 'nan', 'veg', 'carbohydrates', 'NA');
INSERT INTO `item_details` VALUES ('meal_id305', 'sunga pork', 'curry', 'curry', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id306', 'banana chips', 'banana', 'r dried slices of bananas  fruits of herbaceous plants of the genus musa of the soft# sweet \"dessert banana\" variety # they can be covered with sugar or honey and have a sweet taste# or they can be fried in oil and spices and have a salty and/or spicy taste.[2]', 'veg', 'magnesium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id307', 'bhurji- egg', 'egg', 'made using indian spices# onion# tomatoes# green chilli# and had with bread# or parathas.', 'non-veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id308', 'flattened rice / pohe', 'rice', 'ible# dehusked rice which is flattened into flat light dry flakes# these flakes of rice swell when added to liquid# whether hot or cold# as they absorb water# milk# or any other liquids. the thicknesses of these flakes vary between almost translucently thin  the more expensive varieties  to nearly four times thicker than a normal rice grain.', 'veg', 'carbohydrates', 'NA');
INSERT INTO `item_details` VALUES ('meal_id309', 'puffed rice', 'rice', 'grain made from rice; usually made by heating rice kernels under high pressure in the presence of steam# though the method of manufacture varies widely. pori  puffed rice  has been mentioned in various tamil literatures as an offering to hindu deities. offerings of pori and jaggery made to vinayagar  lord ganesh  are mentioned in the tiruppugazh# a 15th-century anthology of tamil religious songs# written by tamil poet arunagirinathar. pori is offered to hindu gods and goddesses in all poojas in the south indian states of kerala and tamil nadu.', 'veg', 'carbohydrates', 'NA');
INSERT INTO `item_details` VALUES ('meal_id31', 'baked almond kofta', 'kofta', 'potato  boiled # nutmeg# milk# almonds  crushed # green onions# refined flour# egg# salt# pepper# eggs# refined flour  for rolling # dried breadcrumbs  for rolling ', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id32', 'almond and amaranth ladoo', 'ladoo', 'popped amaranth seeds# jaggery# almonds  slivered# unpeeled ', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id4', 'tricolour salad', 'salad', 'vinegar# honey/sugar# soy sauce# salt# garlic cloves  minced # chilli pepper  sliced # green papaya# carrot  peeled # cucumbers# mint leaves# toasted peanuts', 'veg', 'fiber', 'NA');
INSERT INTO `item_details` VALUES ('meal_id42', 'sugar free modak', 'snacks', 'seedless dates# almonds# cashew nuts# walnuts# raisins# dry coconut# poppy seeds# ghee', 'veg', 'carbohydrates', 'NA');
INSERT INTO `item_details` VALUES ('meal_id43', 'beetroot modak', 'snacks', 'gram flour  besan # semolina  rava/sooji # beetroot colour or two oven cooked beetroot paste # water# oil  for frying # for sugar syrup:# sugar# water# cardamom powder# lemon juice# cashews  kaju ', 'veg', 'selenium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id44', 'andhra pan fried pomfret', 'snacks', 'white pomfret fish# sunflower refined ooil# red chilli powder# salt# turmeric powder# ginger-garlic paste# lemon  juiced # cumin powder# coriander powder# garam masala# green chilli# curry leaves# coriander', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id45', 'ghee roast chicken dosa quesadilla', 'snacks', 'dry red chillies# coriander seeds# cumin seeds# fenugreek seeds# black pepper# clove# garlic# turmeric powder# boneless chicken# curd# lemon  juiced # for cooking chicken:# tamarind pulp# ginger  1 inch # garlic cloves# onion# tomato# ghee# red chilli powder# salt# crushed jaggery# dosa batter  for 4 dosas # processed cheese# ghee or oil  to crisp the dosa # coriander leaves# curry leaves  deep fried # curd# salt# zeera powder# sugar# red chilli powder', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id46', 'steam bunny chicken bao', 'snacks', 'buns# all purpose white flour# dry yeast# sugar# salt# warm water# chicken mince# eggs# soy sauce# sugar# sesame oil# worcestershire sauce# chives# aromat powder', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id47', 'meat lovers pizza', 'snacks', 'millet flour# tapioca flour# soy milk# garlic powder# baking powder# salt# tomato sauce# mozzarella cheese# prosciutto# pepperoni# chicken salami# salami milano# rosemary# olive oil', 'non-veg', 'potassium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id48', 'almond and chicken momos  without shell ', 'snacks', 'chicken mince# garlic# carrots# spring onion# ginger# soya sauce# oyster sauce# sesame oil# pepper powder# egg# almonds  blanched # oil  for greasing ', 'non-veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id49', 'christmas tree pizza', 'snacks', 'pizza dough  2 boules # red pepper# red onion# basil pesto  purchased# homemade or vegan pesto # mozzarella cheese# kosher salt', 'veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id5', 'gluten-free christmas cake', 'cake', 'christmas dry fruits  pre-soaked # orange zest# lemon zest# jaggery syrup# almond flour# apple# butter  softened # eggs', 'veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id50', 'belgian pork chop', 'snacks', 'pork chop# pink pepper corn# green pepper corn# aromatic sauce# salt# black pepper# salted butter# refined oil# red cabbage# bell pepper chop# apricot# onion# red wine# ancho chilli# cayenne pepper# microgreen', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id51', 'christmas chocolate fudge cookies', 'cookie', 'unsalted butter# brown sugar# chocolate# chocolate chips# eggs# flour# cocoa powder# baking powder', 'veg', 'magnesium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id52', 'chicken parmigiana with tomato sauce', 'snacks', 'for chicken parmigiana:# chicken breast# egg whole frozen# flour# planko bread crumbs# fresh italian parsley# vegetable oil# solid butter unsalted# tomato sauce# mozzarella cheese# italian parmesan cheese# thyme# for pepperonata:# red pepper# green pepper# yellow pepper# red onion# fresh tomato# butternut squash# garlic# pure olive oil# vegetable oil# black pepper corn  crushed # salt# parsley# for garnishing:# parsley sprig# spinach', 'non-veg', 'vitamin_c', 'NA');
INSERT INTO `item_details` VALUES ('meal_id53', 'chocolate appo', 'snacks', 'rice# coconut# baking powder# vanilla extract# cinnamon powder# brown sugar# unsweetened cocoa powder# salt# chocolate chips# butter', 'veg', 'magnesium', 'NA');
INSERT INTO `item_details` VALUES ('Meal_Id530', 'onion salad', 'salad', 'onion#green chilli# salt', 'Veg', 'Fibre', 'cut into pieces and mix well');
INSERT INTO `item_details` VALUES ('meal_id54', 'sous-vide salmon tikka', 'snacks', 'norwegian salmon# black garlic pickle# butter# butchery bag# smoked yogurt# home made prawn crisp# edible flower# salt', 'non-veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id55', 'filo pizza', 'snacks', 'filo pastry# himalayan salt# black pepper# salted butter# tomato sauce# broccoli# button mushroom# green zucchini# yellow zucchini# capsicum yellow# capsicum green# capsicum red# pizza spice mix# mozzarella cheese', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id56', 'chocolate samosa', 'snacks', 'refined flour# desi ghee# black cardamom seeds# chocolate block# almonds# cashew nuts# pistachio# sugar# garam masala powder# oil', 'veg', 'magnesium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id57', 'fish with jamun sauce', 'sauce', 'jamun# sugar# chilli# garlic cloves  minced # cumin  powdered # fish fillet  pomfret  or any white fish # semolina# salt# wilted spinach', 'non-veg', 'vitamin_c', 'NA');
INSERT INTO `item_details` VALUES ('meal_id58', 'dahi lasooni chicken', 'chicken', 'chicken  boneless# cube size # chesse# garlic# ginger garlic paste# coriander# green chilli paste# cream  fresh # curd# kaju paste# salt# black salt # garam masala# chaat masala# butter', 'non-veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id6', 'japanese curry arancini with  barley salsa', 'barley', 'japanese curry# sticky rice# cheese inside rice# barley salsa# wasabi mayo# red capsicum cube  cut # yellow capsicum cube  cut # green capsicum cube  cut # green chily# barley# butter# white pepper# light soya# salt', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id61', 'crunchy vegetable dal sattu croquettes', 'dal', 'red lentils or masoor dal  half-boiled # potato  grated # carrot# french beans# bread slices# ground chickpea flour  sattu # green chillies# ginger# onions# garlic  minced # salt# sugar# chaat masala# red chilli powder# garam masala# corn flour# besan# bread crumbs for crunchyness# coriander# refined oil  for fryingp ', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id62', 'active charcoal modak', 'modak', 'for modak:# gram flour  besan # semolina  rava/suji # active charcoal# water# oil  for frying # sugar# water# cardamom powder# lemon juice# cashews  kaju ', 'veg', 'selenium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id63', 'flax seed and beetroot modak', 'modak', 'rice flour# salt# oil  for greasing # beetroot puree# tossed flax seeds  for topping # fresh coconut# jaggery# poppy seeds# green cardamom powder# nutmeg powder', 'veg', 'magnesium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id64', 'chocolate prunes gujiyas', 'chocolate', 'for gujiya pastry:# refined flour# ghee# water# salt# for gujiya stuffing:# dark chocolate# prunes# mawa# sugar# cardamom', 'veg', 'magnesium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id65', 'almond &amp; white chocolate gujiya', 'gujiya', 'all-purpose flour# clarified butter  ghee # water# white chocolate# dessicated coconut# green cardamom powder# almond# jaggery', 'veg', 'magnesium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id66', 'betel nut popsicle', 'sauce', 'full cream milk# cream# mascarpone# sugar# paan  crushed # cookie crumble# dark chocolate  melted # caramel sauce', 'veg', 'magnesium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id67', 'clotted cottage cheese croquettes', 'cheese', 'black pepper# black salt# bread crumb# corn flour# refined oil# jalapeno# jeera powder# maida# cottage cheese# parsley# salt# for thousand island dressing:# mayonnaise# tomato ketchup# minced garlic# celery# black pepper', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id68', 'gajar halwa tart', 'halwa', 'white butter# breakfast sugar# milk full fat# refined flour# winter carrots# ghee# sugar# khoya# cardamom powder# cashew nuts  crushed # almonds  crushed # full fat milk# full fat milk# grain sugar# green cardamom powder', 'veg', 'vitamin_d', 'NA');
INSERT INTO `item_details` VALUES ('meal_id7', 'chocolate nero cookies', 'cookie', 'almonds# eggs# granulated sugar# bittersweet chocolate# unsalted butter# flour# baking powder# castor sugar# icing sugar', 'veg', 'magnesium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id72', 'dark night', 'apple', 'whisky# honey# cinnamon# star anise# cloves# green apple', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id73', 'hot chocolate', 'chocolate', 'milk# chocolate# cocoa powder# powdered sugar# cinnamon# vanilla', 'veg', 'magnesium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id74', 'slow cooked spiced sangria', 'sangria', 'red wine  merlot / zinfandel # apple cider# honey# orange  zested and juiced # cloves  whole # green cardamom# cinnamon sticks# anise  whole # brandy', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id75', 'detox haldi tea', 'tea', 'haldi# ginger# black pepper# honey# water', 'veg', 'manganese', 'NA');
INSERT INTO `item_details` VALUES ('meal_id76', 'holi special ice tea thandai', 'tea', 'ground white pepper  kali mirch # assam tea bags# almonds  badam  - coarsley crushed# poppy seeds  khus-khus # fennel seeds  saunf   crushed coarsely # cardamom  elaichi  powder# ground sugar# saffron  kesar  strands', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id77', 'grilled lemon margarita', 'margarita', 'vanilla infused tequila# vanilla liqueur# lemon juice# lemon# lemon', 'veg', 'vitamin_c', 'NA');
INSERT INTO `item_details` VALUES ('meal_id78', 'spanish artichoke and spinach dip', 'dip', 'spinach# onion# cream# garlic# nutmeg# salt# lime juice# artichoke hearts  cubed # polenta# refined flour# salt# water# butter# flour# salt# pepper  freshly ground ', 'veg', 'vitamin_c', 'NA');
INSERT INTO `item_details` VALUES ('meal_id79', 'beetroot and green apple soup', 'soup', 'beetroots# green apple# onion# olive oil# salt# black peppercorns  crushed # butter# vegetable stock# mixed dried herbs# fresh cream# lemon juice# parsley sprigs# red chilli flakes# soup sticks as required', 'veg', 'sodium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id8', 'lamb and chargrilled bell pepper soup', 'soup', 'lamb bones  preferably shank and shoulder # onions# celery# ginger# garlic# carrot# chargrilled red/yellow/green bell peppers  quartered # whole spices mix  black pepper# cinnamon# cardamom# clove# bay leaf # salt# water  warm # oil  sunflower or olive', 'non-veg', 'sodium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id80', 'baba budan no. 7', 'cardamom', 'rum# espresso# sugar syrup/gur  jaggery  syrup# green cardamom pod#', 'veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id81', 'fruit infused tea', 'tea', 'chamomile tea bags# orange# berries# blueberries# ginger# mint leaves# boiling water', 'veg', 'manganese', 'NA');
INSERT INTO `item_details` VALUES ('meal_id85', 'garlic and pinenut soup with burnt butter essence', 'soup', 'garlic cloves# almonds  whole # parsley# bayleaf# chicken broth# nutmeg# egg yolk# heavy cream# white bread slices# butter# salt# pepper# white wine', 'non-veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id86', 'roast turkey with cranberry sauce', 'chicken', 'whole turkey# butter# onion# celery# crumbled sage and thyme # salt and pepper# garlic minced# balsamic vinegar# sugar# cranberry', 'non-veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id87', 'roasted spring chicken with root veggies', 'chicken', 'whole chicken# thyme# garlic# lemon# orange# salt# black pepper# butter  to rub # extra olive oil# carrot# turnip# beetroot# chipotle powder# parsley', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id88', 'peri peri chicken satay', 'chicken', 'boneless skinless chicken thigh  trimmed # salt and pepper# yogurt# chilli powder# ginger garlic paste# coriander leaves# oil to fry# peri peri sauce# potato fries', 'non-veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id89', 'chicken popcorn', 'chicken', 'chicken  boneless # corn flour or all purpose flour# egg# bread crumbs# salt# ginger garlic paste# black pepper# onion powder  optional # red chilli powder or paprika or cayenne pepper# oil for deep frying', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id9', 'cream of almond soup', 'soup', 'vegetable stock# skimmed milk# toasted almonds  powdered # butter# flour# salt and pepper# nutmeg# almond essence# toasted almond flakes', 'veg', 'calcium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id90', 'half roast chicken', 'chicken', 'cooking oil# whole chicken  skin on- rinsed and dressed # onions  quartered- skin on # garlic  halved - skin on # carrots  roughly quartered # celery # thyme# dunkleweizen  pour into a glass and keep open at room temperature for an hour or two to make flat # chicken stock# butter# sea salt', 'non-veg', 'vitamin_a', 'NA');
INSERT INTO `item_details` VALUES ('meal_id91', 'riceless chicken biryani', 'chicken', 'malabar peppercorn# cinnamon stick# green cardamom pods# star anise# cloves# fennel seeds# vermicelli# desi ghee# shahi jeera# bay leaves# green chilli# mint leaves# onion# saffron# garlic paste# salt# chicken  dark meat # ginger paste# turmeric powder# coriander powder# red chilli powder# roma tomatoes  de-seedeed # water', 'non-veg', 'vitamin_c', 'NA');
INSERT INTO `item_details` VALUES ('meal_id92', 'chicken farcha', 'chicken', 'boneless chicken thigh  without skin # lemon juice# garlic paste# ginger paste# red chilli powder# coriander powder# garam masala# black pepper  crushed # salt# bread crumbs / semolina# eggs# red chilli powder# oil', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id93', 'buldak  hot and spicy chicken ', 'chicken', 'chicken drum sticks/ chicken breast# soy sauce# sugar# traditional corn syrup  substitution honey # cheong ju  clear rice wine similar to japanese  sake # green onion# black pepper# olive oil# sesame seeds  optional # for marinating sauce:# gochugaru  red chili pepper flakes # alapenos# korean pear  substitution asian pear # onion# garlic# soy sauce# spicy yellow mustard# sesame oil# sugar# mul yut  substitution honey ', 'non-veg', 'magnesium', 'NA');
INSERT INTO `item_details` VALUES ('meal_id94', 'chicken sukka', 'chicken', 'chicken  small pieces # onion  thin slices # cardamom# salt# oil# coriander# cumin# mustard# pepper# cloves# cinnamon# bedki chillies# kashmiri chilies# turmeric# onion# garlic# ginger# salt', 'non-veg', 'chloride', 'NA');
INSERT INTO `item_details` VALUES ('meal_id95', 'steamed chicken roulade', 'chicken', 'lamb mince# garlic # salt# paprika powder# pomodaro tomatoes# olive oil# celery# shallots# carrot# black pepper# bay leaf# yellow chilli powder# cilantro# chicken thigh# salt# white pepper powder# garlic paste# white wine vinegar# olive oil# yellow chilli powder# refined oil# fenugreek seeds# white pepper powder# garlic# fenugreek leaves# onion# broken cashew# salt# fresh cream# kasoori methi', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id96', 'methi chicken masala', 'chicken', 'boneless chicken# lemon juice# red chilli powder# salt# ginger garlic paste# curd# red chilli powder# salt# coriander powder# oil# onion# oil# bay leaf# green cardamom# black cardamom# cinnamon# ginger garlic paste# tomato# kasoori methi# green chilli# water', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id97', 'restaurant style fried chicken', 'chicken', 'egg# salt# white pepper# maida# salt# red chilli powder# garlic powder# ginger powder# onion powder# oregano# chillil flakes# white pepper# basil# chicken drumsticks# salt# white pepper# bread crumbs  as required ', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id98', 'chicken potli', 'chicken', 'chicken# onion# green chilli# garlic# ginger# salt# aromatic powder# soya sauce# oyster sauce# spring onion# filo sheets', 'non-veg', 'iron', 'NA');
INSERT INTO `item_details` VALUES ('meal_id99', 'spicy chicken masala', 'chicken', 'mustard oil# curry leaves# kalonjee# saunf# garlic# onion# tomatoes# ginger# green chillies# boneless chicken# salt# tomato puree# red chilli powder# cumin powder# black salt# peppercorn  crushed # water# mint# coriander', 'non-veg', 'iron', 'NA');
INSERT INTO `login` VALUES ('admin', '123456', 'admin');
INSERT INTO `payment_details` VALUES ('1', '9988776655', 'meal_id9 meal_id79 ', 'cream of almond soup beetroot and green apple soup ', '630.0', '16 Apr, 2023 8:47:59 PM', '1236547896', 'sam', '2025', '1', 'Delivered');
INSERT INTO `payment_details` VALUES ('2', '9988776655', 'meal_id9 meal_id77 meal_id94 meal_id11 ', 'cream of almond soup grilled lemon margarita chicken sukka coconut lime quinoa salad ', '1810.0', '16 Apr, 2023 9:52:26 PM', '12345698745236', 'sam', '2024', '7', 'Delivered');
INSERT INTO `payment_details` VALUES ('3', '9988776655', 'meal_id309 meal_id96 ', 'puffed rice methi chicken masala ', '625.0', '16 Apr, 2023 10:16:08 PM', '1236547896523', 'sam', '2023', '6', 'Delivered');
INSERT INTO `user_details` VALUES ('sumit', 'saha', 'sumit@gmail.com', '9988776655', 'btm', 'Male', '123456');
INSERT INTO `user_favourite_details` VALUES ('9988776655', 'meal_id9');
INSERT INTO `user_favourite_details` VALUES ('9988776655', 'meal_id74');
INSERT INTO `user_favourite_details` VALUES ('9988776655', 'meal_id96');
INSERT INTO `user_favourite_details` VALUES ('9988776655', 'Meal_Id530');
